name: Publish to Github Packages

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.2
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 16.14.2
          registry-url: https://npm.pkg.github.com/
          scope: '@tensingn'
      - run: npm --prefix ./package install
      - run: npm --prefix ./package run build
      - run: npm publish ./package/dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
